In [1]:
import pandas as pd

In [2]:
transaction = pd.DataFrame({
    'Customer_ID': [101, 102, 103, 104, 105],
    'Transaction': [5000, 3000, 4500, 2000, 6000],
    'Product': ['Laptop', 'Phone', 'Tablet', 'Watch', 'Laptop']
})

transaction

   Customer_ID  Transaction Product
0          101         5000  Laptop
1          102         3000   Phone
2          103         4500  Tablet
3          104         2000   Watch
4          105         6000  Laptop

In [3]:
demographic = pd.DataFrame({
    'Customer_ID': [101, 102, 103, 104, 106],
    'Age': [25, 30, 28, 35, 40],
    'City': ['Chennai', 'Bangalore', 'Coimbatore', 'Chennai', 'Madurai']
})

demographic

   Customer_ID  Age        City
0          101   25     Chennai
1          102   30   Bangalore
2          103   28  Coimbatore
3          104   35     Chennai
4          106   40     Madurai

In [4]:
print("Duplicate transaction IDs:")
print(transaction[transaction['Customer_ID'].duplicated()])

print("Duplicate demographic IDs:")
print(demographic[demographic['Customer_ID'].duplicated()])

Duplicate transaction IDs:
Empty DataFrame
Columns: [Customer_ID, Transaction, Product]
Index: []
Duplicate demographic IDs:
Empty DataFrame
Columns: [Customer_ID, Age, City]
Index: []

In [5]:
combined = pd.merge(
    transaction,
    demographic,
    on='Customer_ID',
    how='outer'
)

combined

   Customer_ID  Transaction Product   Age        City
0          101       5000.0  Laptop  25.0     Chennai
1          102       3000.0   Phone  30.0   Bangalore
2          103       4500.0  Tablet  28.0  Coimbatore
3          104       2000.0   Watch  35.0     Chennai
4          105       6000.0  Laptop   NaN         NaN
5          106          NaN     NaN  40.0     Madurai

In [6]:
print(combined.isnull().sum())

Customer_ID    0
Transaction    1
Product        1
Age            1
City           1
dtype: int64

In [7]:
transaction_ids = set(transaction['Customer_ID'])
demographic_ids = set(demographic['Customer_ID'])

print("Only in Transaction:", transaction_ids - demographic_ids)
print("Only in Demographic:", demographic_ids - transaction_ids)

Only in Transaction: {105}
Only in Demographic: {106}

In [8]:
print(combined.groupby('Customer_ID').size())

Customer_ID
101    1
102    1
103    1
104    1
105    1
106    1
dtype: int64

In [9]:
combined = combined.drop_duplicates(subset='Customer_ID')

In [10]:
combined = combined.sort_values('Customer_ID')

In [11]:
combined = combined.reset_index(drop=True)

In [12]:
print("Final Combined Data:")
print(combined)

Final Combined Data:
   Customer_ID  Transaction Product   Age        City
0          101       5000.0  Laptop  25.0     Chennai
1          102       3000.0   Phone  30.0   Bangalore
2          103       4500.0  Tablet  28.0  Coimbatore
3          104       2000.0   Watch  35.0     Chennai
4          105       6000.0  Laptop   NaN         NaN
5          106          NaN     NaN  40.0     Madurai